spring.application.name=metube
spring.security.enabled=false
server.port=${PORT:8080}
spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration,\
org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,\
org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration,\
org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

# ==============================
# Redis (Optional)
# ==============================
app.redis.enabled=${APP_REDIS_ENABLED:false}

# ==============================
# Redis Configuration (Upstash)
# ==============================
spring.data.redis.url=${SPRING_DATA_REDIS_URL:redis://localhost:6379}
spring.data.redis.ssl.enabled=true
spring.cache.type=redis
spring.data.redis.timeout=6000
